#!/bin/bash

echo "Clean, lint check and running Unit test for the project..."

./gradlew clean app:ktlintCheck app:test --daemon

status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0